//
// Created by 谢康 on 2019/1/16.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_org_opencv_samples_fd_DetectionBasedTracker
#define _Included_org_opencv_samples_fd_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeCreateObject
        (JNIEnv *, jclass, jstring, jstring, jint);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeDestroyObject
        (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeStart
        (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeStop
        (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeSetFaceSize
        (JNIEnv *, jclass, jlong, jint);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeDetect
        (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeDetectEyeBlink
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_andrewtse_testdemo_opencv_DetectionBasedTracker_nativeRgba
        (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}

#endif
#endif
